name: 'Convert Excel to CSV files'
description: 'Converts a single Excel file to multiple CSV files (1 per worksheet)'
author: 'Dave Mills (Stats4SD)'
inputs:
  excel_path:  # id of input
    description: 'The pathway from the root of your repository to the Excel file you want to convert'
    required: true
    default: './example.xlsx'
runs:
  using: 'node20'
  main: 'dist/index.js'